language: java
sudo: false

jdk:
  - openjdk8
#  - openjdk11
#  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - ./mvnw clean install -DskipTests=true -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true -q -e
  - ./mvnw cobertura:cobertura -DskipTests=true -Dmaven.javadoc.skip=true -q -e

after_success:
  - bash <(curl -s https://codecov.io/bash)
